// 2026-02-25 21:47

const inArg = $arguments;
const boolArg = (v, d = false) => {
  if (v == null || v === "") return d;
  return /^(true|1|on|yes)$/i.test(v) ? true : /^(false|0|off|no)$/i.test(v) ? false : !!v;
};

const config = {
  clear: boolArg(inArg.clear, true),
  flag:  boolArg(inArg.flag, true),
  fgf:   inArg.fgf ? decodeURI(inArg.fgf) : " ",
};

const RE_CLEAR = /(GB|TB|免费|套餐|到期|剩余|过期|测试|官网|订阅|流量|机场|联系|客服|有效|重置|网站|地址)/i;
const RE_HOME = /(家宽|住宅|ISP|Home|Residential)/i;

const REGIONS = [
  { re: /香港|HK|Hong\s?Kong|🇭🇰/i, name: "香港", emoji: "🇭🇰" },
  { re: /台湾|TW|Taiwan|🇹🇼/i, name: "台湾", emoji: "🇨🇳" },
  { re: /澳门|MO|Macao|🇲🇴/i, name: "澳门", emoji: "🇲🇴" },
  { re: /日本|JP|Japan|🇯🇵/i, name: "日本", emoji: "🇯🇵" },
  { re: /韩国|KR|Korea|🇰🇷/i, name: "韩国", emoji: "🇰🇷" },
  { re: /新加坡|SG|Singapore|🇸🇬/i, name: "新加坡", emoji: "🇸🇬" },
  { re: /美国|US|USA|United\s?States|🇺🇸/i, name: "美国", emoji: "🇺🇸" },
  { re: /英国|UK|United\s?Kingdom|Britain|🇬🇧/i, name: "英国", emoji: "🇬🇧" },
  { re: /越南|VN|Vietnam|🇻🇳/i, name: "越南", emoji: "🇻🇳" },
  { re: /德国|DE|Germany|🇩🇪/i, name: "德国", emoji: "🇩🇪" },
  { re: /法国|FR|France|🇫🇷/i, name: "法国", emoji: "🇫🇷" },
  { re: /俄罗斯|RU|Russia|🇷🇺/i, name: "俄罗斯", emoji: "🇷🇺" },
  { re: /泰国|TH|Thailand|🇹🇭/i, name: "泰国", emoji: "🇹🇭" },
  { re: /菲律宾|PH|Philippines|🇵🇭/i, name: "菲律宾", emoji: "🇵🇭" },
  { re: /马来西亚|MY|Malaysia|🇲🇾/i, name: "马来西亚", emoji: "🇲🇾" },
  { re: /土耳其|TR|Turkey|🇹🇷/i, name: "土耳其", emoji: "🇹🇷" },
  { re: /印度|IN|India|🇮🇳/i, name: "印度", emoji: "🇮🇳" },
  { re: /印尼|ID|Indonesia|🇮🇩/i, name: "印尼", emoji: "🇮🇩" },
  { re: /以色列|IL|Israel|🇮🇱/i, name: "以色列", emoji: "🇮🇱" },
  { re: /亚美尼亚|AM|Armenia/i, name: "亚美尼亚", emoji: "🇦🇲" },
  { re: /澳大利亚|AU|Australia|🇦🇺/i, name: "澳大利亚", emoji: "🇦🇺" },
  { re: /新西兰|NZ|New\s?Zealand|🇳🇿/i, name: "新西兰", emoji: "🇳🇿" },
  { re: /加拿大|CA|Canada|🇨🇦/i, name: "加拿大", emoji: "🇨🇦" },
  { re: /墨西哥|MX|Mexico|🇲🇽/i, name: "墨西哥", emoji: "🇲🇽" },
  { re: /巴西|BR|Brazil|🇧🇷/i, name: "巴西", emoji: "🇧🇷" },
  { re: /阿根廷|AR|Argentina|🇦🇷/i, name: "阿根廷", emoji: "🇦🇷" },
  { re: /智利|CL|Chile|🇨🇱/i, name: "智利", emoji: "🇨🇱" },
  { re: /哥伦比亚|CO|Colombia|🇨🇴/i, name: "哥伦比亚", emoji: "🇨🇴" },
  { re: /秘鲁|PE|Peru|🇵🇪/i, name: "秘鲁", emoji: "🇵🇪" },
  { re: /意大利|IT|Italy|🇮🇹/i, name: "意大利", emoji: "🇮🇹" },
  { re: /西班牙|ES|Spain|🇪🇸/i, name: "西班牙", emoji: "🇪🇸" },
  { re: /荷兰|NL|Netherlands|🇳🇱/i, name: "荷兰", emoji: "🇳🇱" },
  { re: /瑞士|CH|Switzerland|🇨🇭/i, name: "瑞士", emoji: "🇨🇭" },
  { re: /瑞典|SE|Sweden|🇸🇪/i, name: "瑞典", emoji: "🇸🇪" },
  { re: /挪威|NO|Norway|🇳🇴/i, name: "挪威", emoji: "🇳🇴" },
  { re: /丹麦|DK|Denmark|🇩🇰/i, name: "丹麦", emoji: "🇩🇰" },
  { re: /芬兰|FI|Finland|🇫🇮/i, name: "芬兰", emoji: "🇫🇮" },
  { re: /奥地利|AT|Austria|🇦🇹/i, name: "奥地利", emoji: "🇦🇹" },
  { re: /比利时|BE|Belgium|🇧🇪/i, name: "比利时", emoji: "🇧🇪" },
  { re: /爱尔兰|IE|Ireland|🇮🇪/i, name: "爱尔兰", emoji: "🇮🇪" },
  { re: /葡萄牙|PT|Portugal|🇵🇹/i, name: "葡萄牙", emoji: "🇵🇹" },
  { re: /希腊|GR|Greece|🇬🇷/i, name: "希腊", emoji: "🇬🇷" },
  { re: /捷克|CZ|Czech|🇨🇿/i, name: "捷克", emoji: "🇨🇿" },
  { re: /波兰|PL|Poland|🇵🇱/i, name: "波兰", emoji: "🇵🇱" },
  { re: /乌克兰|UA|Ukraine|🇺🇦/i, name: "乌克兰", emoji: "🇺🇦" },
  { re: /罗马尼亚|RO|Romania|🇷🇴/i, name: "罗马尼亚", emoji: "🇷🇴" },
  { re: /匈牙利|HU|Hungary|🇭🇺/i, name: "匈牙利", emoji: "🇭🇺" },
  { re: /阿联酋|AE|UAE|🇦🇪/i, name: "阿联酋", emoji: "🇦🇪" },
  { re: /沙特|SA|Saudi\s?Arabia|🇸🇦/i, name: "沙特", emoji: "🇸🇦" },
  { re: /南非|ZA|South\s?Africa|🇿🇦/i, name: "南非", emoji: "🇿🇦" },
  { re: /埃及|EG|Egypt|🇪🇬/i, name: "埃及", emoji: "🇪🇬" },
  { re: /柬埔寨|KH|Cambodia|🇰🇭/i, name: "柬埔寨", emoji: "🇰🇭" },
  { re: /缅甸|MM|Myanmar|🇲🇲/i, name: "缅甸", emoji: "🇲🇲" },
  { re: /老挝|LA|Laos|🇱🇦/i, name: "老挝", emoji: "🇱🇦" },
  { re: /巴基斯坦|PK|Pakistan|🇵🇰/i, name: "巴基斯坦", emoji: "🇵🇰" },
  { re: /哈萨克斯坦|KZ|Kazakhstan|🇰🇿/i, name: "哈萨克斯坦", emoji: "🇰🇿" },
  { re: /乌兹别克斯坦|UZ|Uzbekistan|🇺🇿/i, name: "乌兹别克斯坦", emoji: "🇺🇿" },
  { re: /约旦|JO|Jordan|🇯🇴/i, name: "约旦", emoji: "🇯🇴" },
  { re: /卡塔尔|QA|Qatar|🇶🇦/i, name: "卡塔尔", emoji: "🇶🇦" },
  { re: /科威特|KW|Kuwait|🇰🇼/i, name: "科威特", emoji: "🇰🇼" },
  { re: /孟加拉|BD|Bangladesh|🇧🇩/i, name: "孟加拉", emoji: "🇧🇩" },
  { re: /斯里兰卡|LK|Sri\s?Lanka|🇱🇰/i, name: "斯里兰卡", emoji: "🇱🇰" },
  { re: /尼泊尔|NP|Nepal|🇳🇵/i, name: "尼泊尔", emoji: "🇳🇵" },
  { re: /蒙古|MN|Mongolia|🇲🇳/i, name: "蒙古", emoji: "🇲🇳" },
  { re: /马尔代夫|MV|Maldives|🇲🇻/i, name: "马尔代夫", emoji: "🇲🇻" },
  { re: /不丹|BT|Bhutan|🇧🇹/i, name: "不丹", emoji: "🇧🇹" },
  { re: /文莱|BN|Brunei|🇧🇳/i, name: "文莱", emoji: "🇧🇳" },
  { re: /阿富汗|AF|Afghanistan|🇦🇫/i, name: "阿富汗", emoji: "🇦🇫" },
  { re: /伊拉克|IQ|Iraq|🇮🇶/i, name: "伊拉克", emoji: "🇮🇶" },
  { re: /黎巴嫩|LB|Lebanon|🇱🇧/i, name: "黎巴嫩", emoji: "🇱🇧" },
  { re: /也门|YE|Yemen|🇾🇪/i, name: "也门", emoji: "🇾🇪" },
  { re: /阿曼|OM|Oman|🇴🇲/i, name: "阿曼", emoji: "🇴🇲" },
  { re: /巴林|BH|Bahrain|🇧🇭/i, name: "巴林", emoji: "🇧🇭" },
  { re: /格鲁吉亚|GE|Georgia|🇬🇪/i, name: "格鲁吉亚", emoji: "🇬🇪" },
  { re: /阿塞拜疆|AZ|Azerbaijan|🇦🇿/i, name: "阿塞拜疆", emoji: "🇦🇿" },
  { re: /土库曼斯坦|TM|Turkmenistan|🇹🇲/i, name: "土库曼斯坦", emoji: "🇹🇲" },
  { re: /塔吉克斯坦|TJ|Tajikistan|🇹🇯/i, name: "塔吉克斯坦", emoji: "🇹🇯" },
  { re: /吉尔吉斯斯坦|KG|Kyrgyzstan|🇰🇬/i, name: "吉尔吉斯斯坦", emoji: "🇰🇬" },
  { re: /塞浦路斯|CY|Cyprus|🇨🇾/i, name: "塞浦路斯", emoji: "🇨🇾" },
  { re: /冰岛|IS|Iceland|🇮🇸/i, name: "冰岛", emoji: "🇮🇸" },
  { re: /卢森堡|LU|Luxembourg|🇱🇺/i, name: "卢森堡", emoji: "🇱🇺" },
  { re: /斯洛伐克|SK|Slovakia|🇸🇰/i, name: "斯洛伐克", emoji: "🇸🇰" },
  { re: /保加利亚|BG|Bulgaria|🇧🇬/i, name: "保加利亚", emoji: "🇧🇬" },
  { re: /克罗地亚|HR|Croatia|🇭🇷/i, name: "克罗地亚", emoji: "🇭🇷" },
  { re: /斯洛文尼亚|SI|Slovenia|🇸🇮/i, name: "斯洛文尼亚", emoji: "🇸🇮" },
  { re: /爱沙尼亚|EE|Estonia|🇪🇪/i, name: "爱沙尼亚", emoji: "🇪🇪" },
  { re: /拉脱维亚|LV|Latvia|🇱🇻/i, name: "拉脱维亚", emoji: "🇱🇻" },
  { re: /立陶宛|LT|Lithuania|🇱🇹/i, name: "立陶宛", emoji: "🇱🇹" },
  { re: /白俄罗斯|BY|Belarus|🇧🇾/i, name: "白俄罗斯", emoji: "🇧🇾" },
  { re: /摩尔多瓦|MD|Moldova|🇲🇩/i, name: "摩尔多瓦", emoji: "🇲🇩" },
  { re: /阿尔巴尼亚|AL|Albania|🇦🇱/i, name: "阿尔巴尼亚", emoji: "🇦🇱" },
  { re: /波黑|BA|Bosnia|🇧🇦/i, name: "波黑", emoji: "🇧🇦" },
  { re: /黑山|ME|Montenegro|🇲🇪/i, name: "黑山", emoji: "🇲🇪" },
  { re: /北马其顿|MK|Macedonia|🇲🇰/i, name: "北马其顿", emoji: "🇲🇰" },
  { re: /马耳他|MT|Malta|🇲🇹/i, name: "马耳他", emoji: "🇲🇹" },
  { re: /摩纳哥|MC|Monaco|🇲🇨/i, name: "摩纳哥", emoji: "🇲🇨" },
  { re: /安道尔|AD|Andorra|🇦🇩/i, name: "安道尔", emoji: "🇦🇩" },
  { re: /列支敦士登|LI|Liechtenstein|🇱🇮/i, name: "列支敦士登", emoji: "🇱🇮" },
  { re: /圣马力诺|SM|San\s?Marino|🇸🇲/i, name: "圣马力诺", emoji: "🇸🇲" },
  { re: /梵蒂冈|VA|Vatican|🇻🇦/i, name: "梵蒂冈", emoji: "🇻🇦" },
  { re: /马恩岛|IM|Isle\s?of\s?Man|🇮🇲/i, name: "马恩岛", emoji: "🇮🇲" },
  { re: /泽西岛|JE|Jersey|🇯🇪/i, name: "泽西岛", emoji: "🇯🇪" },
  { re: /根西岛|GG|Guernsey|🇬🇬/i, name: "根西岛", emoji: "🇬🇬" },
  { re: /法罗群岛|FO|Faroe|🇫🇴/i, name: "法罗群岛", emoji: "🇫🇴" },
  { re: /直布罗陀|GI|Gibraltar|🇬🇮/i, name: "直布罗陀", emoji: "🇬🇮" },
  { re: /格陵兰|GL|Greenland|🇬🇱/i, name: "格陵兰", emoji: "🇬🇱" },
  { re: /巴拿马|PA|Panama|🇵🇦/i, name: "巴拿马", emoji: "🇵🇦" },
  { re: /哥斯达黎加|CR|Costa\s?Rica|🇨🇷/i, name: "哥斯达黎加", emoji: "🇨🇷" },
  { re: /危地马拉|GT|Guatemala|🇬🇹/i, name: "危地马拉", emoji: "🇬🇹" },
  { re: /洪都拉斯|HN|Honduras|🇭🇳/i, name: "洪都拉斯", emoji: "🇭🇳" },
  { re: /萨尔瓦多|SV|Salvador|🇸🇻/i, name: "萨尔瓦多", emoji: "🇸🇻" },
  { re: /尼加拉瓜|NI|Nicaragua|🇳🇮/i, name: "尼加拉瓜", emoji: "🇳🇮" },
  { re: /古巴|CU|Cuba|🇨🇺/i, name: "古巴", emoji: "🇨🇺" },
  { re: /多米尼加|DO|Dominican|🇩🇴/i, name: "多米尼加", emoji: "🇩🇴" },
  { re: /波多黎各|PR|Puerto\s?Rico|🇵🇷/i, name: "波多黎各", emoji: "🇵🇷" },
  { re: /牙买加|JM|Jamaica|🇯🇲/i, name: "牙买加", emoji: "🇯🇲" },
  { re: /特立尼达|TT|Trinidad|🇹🇹/i, name: "特立尼达和多巴哥", emoji: "🇹🇹" },
  { re: /巴哈马|BS|Bahamas|🇧🇸/i, name: "巴哈马", emoji: "🇧🇸" },
  { re: /巴巴多斯|BB|Barbados|🇧🇧/i, name: "巴巴多斯", emoji: "🇧🇧" },
  { re: /圣卢西亚|LC|Saint\s?Lucia|🇱🇨/i, name: "圣卢西亚", emoji: "🇱🇨" },
  { re: /格林纳达|GD|Grenada|🇬🇩/i, name: "格林纳达", emoji: "🇬🇩" },
  { re: /乌拉圭|UY|Uruguay|🇺🇾/i, name: "乌拉圭", emoji: "🇺🇾" },
  { re: /巴拉圭|PY|Paraguay|🇵🇾/i, name: "巴拉圭", emoji: "🇵🇾" },
  { re: /玻利维亚|BO|Bolivia|🇧🇴/i, name: "玻利维亚", emoji: "🇧🇴" },
  { re: /厄瓜多尔|EC|Ecuador|🇪🇨/i, name: "厄瓜多尔", emoji: "🇪🇨" },
  { re: /委内瑞拉|VE|Venezuela|🇻🇪/i, name: "委内瑞拉", emoji: "🇻🇪" },
  { re: /圭亚那|GY|Guyana|🇬🇾/i, name: "圭亚那", emoji: "🇬🇾" },
  { re: /苏里南|SR|Suriname|🇸🇷/i, name: "苏里南", emoji: "🇸🇷" },
  { re: /阿尔及利亚|DZ|Algeria|🇩🇿/i, name: "阿尔及利亚", emoji: "🇩🇿" },
  { re: /摩洛哥|MA|Morocco|🇲🇦/i, name: "摩洛哥", emoji: "🇲🇦" },
  { re: /突尼斯|TN|Tunisia|🇹🇳/i, name: "突尼斯", emoji: "🇹🇳" },
  { re: /利比亚|LY|Libya|🇱🇾/i, name: "利比亚", emoji: "🇱🇾" },
  { re: /尼日利亚|NG|Nigeria|🇳🇬/i, name: "尼日利亚", emoji: "🇳🇬" },
  { re: /加纳|GH|Ghana|🇬🇭/i, name: "加纳", emoji: "🇬🇭" },
  { re: /肯尼亚|KE|Kenya|🇰🇪/i, name: "肯尼亚", emoji: "🇰🇪" },
  { re: /坦桑尼亚|TZ|Tanzania|🇹🇿/i, name: "坦桑尼亚", emoji: "🇹🇿" },
  { re: /乌干达|UG|Uganda|🇺🇬/i, name: "乌干达", emoji: "🇺🇬" },
  { re: /埃塞尾比亚|ET|Ethiopia|🇪🇹/i, name: "埃塞俄比亚", emoji: "🇪🇹" },
  { re: /苏丹|SD|Sudan|🇸🇩/i, name: "苏丹", emoji: "🇸🇩" },
  { re: /科特迪瓦|CI|Ivory\s?Coast|🇨🇮/i, name: "科特迪瓦", emoji: "🇨🇮" },
  { re: /喀麦隆|CM|Cameroon|🇨🇲/i, name: "喀麦隆", emoji: "🇨🇲" },
  { re: /安哥拉|AO|Angola|🇦🇴/i, name: "安哥拉", emoji: "🇦🇴" },
  { re: /赞比亚|ZM|Zambia|🇿🇲/i, name: "赞比亚", emoji: "🇿🇲" },
  { re: /津巴布韦|ZW|Zimbabwe|🇿🇼/i, name: "津巴布韦", emoji: "🇿🇼" },
  { re: /博茨瓦纳|BW|Botswana|🇧🇼/i, name: "博茨瓦纳", emoji: "🇧🇼" },
  { re: /纳米比亚|NA|Namibia|🇳🇦/i, name: "纳米比亚", emoji: "🇳🇦" },
  { re: /马达加斯加|MG|Madagascar|🇲🇬/i, name: "马达加斯加", emoji: "🇲🇬" },
  { re: /塞尔维亚|RS|Serbia|🇷🇸/i, name: "塞尔维亚", emoji: "🇷🇸" },
  { re: /朝鲜|KP|North\s?Korea|🇰🇵/i, name: "朝鲜", emoji: "🇰🇵" },
  { re: /叙利亚|SY|Syria|🇸🇾/i, name: "叙利亚", emoji: "🇸🇾" },
  { re: /东帝汶|TL|Timor|🇹🇱/i, name: "东帝汶", emoji: "🇹🇱" },
  { re: /中非|CF|Central\s?African|🇨🇫/i, name: "中非共和国", emoji: "🇨🇫" },
  { re: /伯利兹|BZ|Belize|🇧🇿/i, name: "伯利兹", emoji: "🇧🇿" },
  { re: /安提瓜|AG|Antigua|🇦🇬/i, name: "安提瓜和巴布达", emoji: "🇦🇬" },
  { re: /圣基茨|KN|Saint\s?Kitts|🇰🇳/i, name: "圣基茨和尼维斯", emoji: "🇰🇳" },
  { re: /圣文森特|VC|Saint\s?Vincent|🇻🇨/i, name: "圣文森特和格林纳丁斯", emoji: "🇻🇨" },
  { re: /多米尼克|DM|🇩🇲/i, name: "多米尼克", emoji: "🇩🇲" },
  { re: /库克群岛|CK|Cook\s?Islands|🇨🇰/i, name: "库克群岛", emoji: "🇨🇰" },
  { re: /纽埃|NU|Niue|🇳🇺/i, name: "纽埃", emoji: "🇳🇺" },
  { re: /科索沃|XK|Kosovo|🇽🇰/i, name: "科索沃", emoji: "🇽🇰" },
  { re: /阿鲁巴|AW|Aruba|🇦🇼/i, name: "阿鲁巴", emoji: "🇦🇼" },
  { re: /百慕大|BM|Bermuda|🇧🇲/i, name: "百慕大", emoji: "🇧🇲" },
  { re: /开曼群岛|KY|Cayman|🇰🇾/i, name: "开曼群岛", emoji: "🇰🇾" },
  { re: /库拉索|CW|Curacao|🇨🇼/i, name: "库拉索", emoji: "🇨🇼" },
  { re: /波利尼西亚|PF|Polynesia|🇵🇫/i, name: "法属波利尼西亚", emoji: "🇵🇫" },
  { re: /冈比亚|GM|Gambia|🇬🇲/i, name: "冈比亚", emoji: "🇬🇲" },
  { re: /几内亚比绍|GW|Bissau|🇬🇼/i, name: "几内亚比绍", emoji: "🇬🇼" },
  { re: /利比里亚|LR|Liberia|🇱🇷/i, name: "利比里亚", emoji: "🇱🇷" },
  { re: /马拉维|MW|Malawi|🇲🇼/i, name: "马拉维", emoji: "🇲🇼" },
  { re: /马里|ML|Mali|🇲🇱/i, name: "马里", emoji: "🇲🇱" },
  { re: /毛里塔尼亚|MR|Mauritania|🇲🇷/i, name: "毛里塔尼亚", emoji: "🇲🇷" },
  { re: /尼日尔|NE|Niger|🇳🇪/i, name: "尼日尔", emoji: "🇳🇪" },
  { re: /多哥|TG|Togo|🇹🇬/i, name: "多哥", emoji: "🇹🇬" },
  { re: /塞拉利昂|SL|Sierra\s?Leone|🇸🇱/i, name: "塞拉利昂", emoji: "🇸🇱" },
  { re: /瓦努阿图|VU|Vanuatu|🇻🇺/i, name: "瓦努阿图", emoji: "🇻🇺" },
  { re: /汤加|TO|Tonga|🇹🇴/i, name: "汤加", emoji: "🇹🇴" },
  { re: /萨摩亚|WS|Samoa|🇼🇸/i, name: "萨摩亚", emoji: "🇼🇸" },
  { re: /所罗门群岛|SB|Solomon|🇸🇧/i, name: "所罗门群岛", emoji: "🇸🇧" },
  { re: /毛里求斯|MU|Mauritius|🇲🇺/i, name: "毛里求斯", emoji: "🇲🇺" },
  { re: /塞舌尔|SC|Seychelles|🇸🇨/i, name: "塞舌尔", emoji: "🇸🇨" },
  { re: /塞内加尔|SN|Senegal|🇸🇳/i, name: "塞内加尔", emoji: "🇸🇳" },
  { re: /布基纳法索|BF|Burkina|🇧🇫/i, name: "布基纳法索", emoji: "🇧🇫" },
  { re: /乍得|TD|Chad|🇹🇩/i, name: "乍得", emoji: "🇹🇩" },
  { re: /贝宁|BJ|Benin|🇧🇯/i, name: "贝宁", emoji: "🇧🇯" },
  { re: /几内亚|GN|Guinea|🇬🇳/i, name: "几内亚", emoji: "🇬🇳" },
  { re: /赤道几内亚|GQ|Equatorial|🇬🇶/i, name: "赤道几内亚", emoji: "🇬🇶" },
  { re: /加蓬|GA|Gabon|🇬🇦/i, name: "加蓬", emoji: "🇬🇦" },
  { re: /刚果（布）|CG|Congo|🇨🇬/i, name: "刚果（布)", emoji: "🇨🇬" },
  { re: /刚果（金）|CD|Kinshasa|🇨🇩/i, name: "刚果（金)", emoji: "🇨🇩" },
  { re: /莫桑比克|MZ|Mozambique|🇲🇿/i, name: "莫桑比克", emoji: "🇲🇿" },
  { re: /佛得角|CV|Cape\s?Verde|🇨🇻/i, name: "佛得角", emoji: "🇨🇻" },
  { re: /吉布提|DJ|Djibouti|🇩🇯/i, name: "吉布提", emoji: "🇩🇯" },
  { re: /索马里|SO|Somalia|🇸🇴/i, name: "索马里", emoji: "🇸🇴" },
  { re: /斐济|FJ|Fiji|🇫🇯/i, name: "斐济", emoji: "🇫🇯" },
  { re: /巴布亚|PG|Papua|🇵🇬/i, name: "巴布亚新几内亚", emoji: "🇵🇬" },
  { re: /关岛|GU|Guam|🇬🇺/i, name: "关岛", emoji: "🇬🇺" },
  { re: /新喀里多尼亚|NC|Caledonia|🇳🇨/i, name: "新喀里多尼亚", emoji: "🇳🇨" },
  { re: /南极|AQ|Antarctica|🇦🇶/i, name: "南极洲", emoji: "🇦🇶" },
  { re: /巴勒斯坦|PS|Palestine|🇵🇸/i, name: "巴勒斯坦", emoji: "🇵🇸" },
  { re: /留尼汪|RE|Reunion|🇷🇪/i, name: "留尼汪", emoji: "🇷🇪" },
  { re: /马提尼克|MQ|Martinique|🇲🇶/i, name: "马提尼克", emoji: "🇲🇶" },
  { re: /瓜德罗普|GP|Guadeloupe|🇬🇵/i, name: "瓜德罗普", emoji: "🇬🇵" },
  { re: /马约特|YT|Mayotte|🇾🇹/i, name: "马约特", emoji: "🇾🇹" },
  { re: /法属圭亚那|GF|French\s?Guiana|🇬🇫/i, name: "法属圭亚那", emoji: "🇬🇫" },
  { re: /维尔京群岛|VG|Virgin\s?Islands|🇻🇬/i, name: "英属维尔京群岛", emoji: "🇻🇬" },
  { re: /美属维尔京|VI|United\s?States\s?Virgin|🇻🇮/i, name: "美属维尔京群岛", emoji: "🇻🇮" },
  { re: /特克斯|TC|Turks|🇹🇨/i, name: "特克斯和凯科斯", emoji: "🇹🇨" },
  { re: /安圭拉|AI|Anguilla|🇦🇮/i, name: "安圭拉", emoji: "🇦🇮" },
  { re: /圣皮埃尔|PM|Miquelon|🇵🇲/i, name: "圣皮埃尔和密克隆", emoji: "🇵🇲" },
  { re: /中国|CN|China|🇨🇳/i, name: "中国大陆", emoji: "🇨🇳" }
];

function operator(pro) {
  const counts = {};
  return pro
    .filter(p => !(config.clear && RE_CLEAR.test(p.name)))
    .map(p => {
      let matched = REGIONS.find(r => r.re.test(p.name));
      
      if (!matched) return p;

      const isHome = RE_HOME.test(p.name);
      
      counts[matched.name] = (counts[matched.name] || 0) + 1;
      const num = String(counts[matched.name]).padStart(2, '0');

      const parts = [];
      if (config.flag) parts.push(matched.emoji);
      parts.push(matched.name);
      parts.push(num);
      if (isHome) parts.push("家宽");

      p.name = parts.join(config.fgf);
      return p;
    })
    .filter(p => p !== null);
}
