// 2024-12-09 20:25

const inArg = $arguments;
const boolArg = (v, d = false) => {
  if (v == null || v === "") return d;
  return /^(true|1|on|yes)$/i.test(v) ? true : /^(false|0|off|no)$/i.test(v) ? false : !!v;
};

const config = {
  clear: boolArg(inArg.clear, true),
  flag:  boolArg(inArg.flag, true),
  fgf:   inArg.fgf ? decodeURI(inArg.fgf) : " ",
};

const RE_CLEAR = /(.com|网址|Traffic|Expire|续费|到期|剩余|魔法|订阅|流量|机场|客户端|下载|有效|防失联|公告|加群|通知|频道)/i;
const RE_HOME = /(家宽|住宅|ISP|Home|Residential)/i;

const REGIONS = [
  { re: /🇭🇰/i, name: "香港", emoji: "🇭🇰" },
  { re: /🇹🇼/i, name: "台湾", emoji: "🇨🇳" },
  { re: /🇲🇴/i, name: "澳门", emoji: "🇲🇴" },
  { re: /🇯🇵/i, name: "日本", emoji: "🇯🇵" },
  { re: /🇰🇵/i, name: "朝鲜", emoji: "🇰🇵" },
  { re: /🇰🇷/i, name: "韩国", emoji: "🇰🇷" },
  { re: /🇸🇬/i, name: "新加坡", emoji: "🇸🇬" },
  { re: /🇺🇸/i, name: "美国", emoji: "🇺🇸" },
  { re: /🇬🇧/i, name: "英国", emoji: "🇬🇧" },
  { re: /🇻🇳/i, name: "越南", emoji: "🇻🇳" },
  { re: /🇩🇪/i, name: "德国", emoji: "🇩🇪" },
  { re: /🇫🇷/i, name: "法国", emoji: "🇫🇷" },
  { re: /🇷🇺/i, name: "俄罗斯", emoji: "🇷🇺" },
  { re: /🇹🇭/i, name: "泰国", emoji: "🇹🇭" },
  { re: /🇵🇭/i, name: "菲律宾", emoji: "🇵🇭" },
  { re: /🇲🇾/i, name: "马来西亚", emoji: "🇲🇾" },
  { re: /🇹🇷/i, name: "土耳其", emoji: "🇹🇷" },
  { re: /🇮🇴/i, name: "英属印度洋领地", emoji: "🇮🇴" },
  { re: /🇮🇳/i, name: "印度", emoji: "🇮🇳" },
  { re: /🇮🇩/i, name: "印尼", emoji: "🇮🇩" },
  { re: /🇮🇱/i, name: "以色列", emoji: "🇮🇱" },
  { re: /🇦🇲/i, name: "亚美尼亚", emoji: "🇦🇲" },
  { re: /🇦🇺/i, name: "澳大利亚", emoji: "🇦🇺" },
  { re: /🇳🇿/i, name: "新西兰", emoji: "🇳🇿" },
  { re: /🇨🇦/i, name: "加拿大", emoji: "🇨🇦" },
  { re: /🇲🇽/i, name: "墨西哥", emoji: "🇲🇽" },
  { re: /🇧🇷/i, name: "巴西", emoji: "🇧🇷" },
  { re: /🇦🇷/i, name: "阿根廷", emoji: "🇦🇷" },
  { re: /🇨🇱/i, name: "智利", emoji: "🇨🇱" },
  { re: /🇨🇴/i, name: "哥伦比亚", emoji: "🇨🇴" },
  { re: /🇵🇪/i, name: "秘鲁", emoji: "🇵🇪" },
  { re: /🇮🇹/i, name: "意大利", emoji: "🇮🇹" },
  { re: /🇪🇸/i, name: "西班牙", emoji: "🇪🇸" },
  { re: /🇳🇱/i, name: "荷兰", emoji: "🇳🇱" },
  { re: /🇨🇭/i, name: "瑞士", emoji: "🇨🇭" },
  { re: /🇸🇪/i, name: "瑞典", emoji: "🇸🇪" },
  { re: /🇳🇴/i, name: "挪威", emoji: "🇳🇴" },
  { re: /🇩🇰/i, name: "丹麦", emoji: "🇩🇰" },
  { re: /🇫🇮/i, name: "芬兰", emoji: "🇫🇮" },
  { re: /🇦🇹/i, name: "奥地利", emoji: "🇦🇹" },
  { re: /🇧🇪/i, name: "比利时", emoji: "🇧🇪" },
  { re: /🇮🇪/i, name: "爱尔兰", emoji: "🇮🇪" },
  { re: /🇵🇹/i, name: "葡萄牙", emoji: "🇵🇹" },
  { re: /🇬🇷/i, name: "希腊", emoji: "🇬🇷" },
  { re: /🇨🇿/i, name: "捷克", emoji: "🇨🇿" },
  { re: /🇵🇱/i, name: "波兰", emoji: "🇵🇱" },
  { re: /🇺🇦/i, name: "乌克兰", emoji: "🇺🇦" },
  { re: /🇷🇴/i, name: "罗马尼亚", emoji: "🇷🇴" },
  { re: /🇭🇺/i, name: "匈牙利", emoji: "🇭🇺" },
  { re: /🇦🇪/i, name: "阿联酋", emoji: "🇦🇪" },
  { re: /🇸🇦/i, name: "沙特阿拉伯", emoji: "🇸🇦" },
  { re: /🇿🇦/i, name: "南非", emoji: "🇿🇦" },
  { re: /🇪🇬/i, name: "埃及", emoji: "🇪🇬" },
  { re: /🇰🇭/i, name: "柬埔寨", emoji: "🇰🇭" },
  { re: /🇲🇲/i, name: "缅甸", emoji: "🇲🇲" },
  { re: /🇱🇦/i, name: "老挝", emoji: "🇱🇦" },
  { re: /🇵🇰/i, name: "巴基斯坦", emoji: "🇵🇰" },
  { re: /🇰🇿/i, name: "哈萨克斯坦", emoji: "🇰🇿" },
  { re: /🇺🇿/i, name: "乌兹别克斯坦", emoji: "🇺🇿" },
  { re: /🇯🇴/i, name: "约旦", emoji: "🇯🇴" },
  { re: /🇶🇦/i, name: "卡塔尔", emoji: "🇶🇦" },
  { re: /🇰🇼/i, name: "科威特", emoji: "🇰🇼" },
  { re: /🇧🇩/i, name: "孟加拉", emoji: "🇧🇩" },
  { re: /🇱🇰/i, name: "斯里兰卡", emoji: "🇱🇰" },
  { re: /🇳🇵/i, name: "尼泊尔", emoji: "🇳🇵" },
  { re: /🇲🇳/i, name: "蒙古", emoji: "🇲🇳" },
  { re: /🇲🇻/i, name: "马尔代夫", emoji: "🇲🇻" },
  { re: /🇧🇹/i, name: "不丹", emoji: "🇧🇹" },
  { re: /🇧🇳/i, name: "文莱", emoji: "🇧🇳" },
  { re: /🇦🇫/i, name: "阿富汗", emoji: "🇦🇫" },
  { re: /🇮🇶/i, name: "伊拉克", emoji: "🇮🇶" },
  { re: /🇮🇷/i, name: "伊朗", emoji: "🇮🇷" },
  { re: /🇱🇧/i, name: "黎巴嫩", emoji: "🇱🇧" },
  { re: /🇾🇪/i, name: "也门", emoji: "🇾🇪" },
  { re: /🇴🇲/i, name: "阿曼", emoji: "🇴🇲" },
  { re: /🇧🇭/i, name: "巴林", emoji: "🇧🇭" },
  { re: /🇬🇪/i, name: "格鲁吉亚", emoji: "🇬🇪" },
  { re: /🇦🇿/i, name: "阿塞拜疆", emoji: "🇦🇿" },
  { re: /🇹🇲/i, name: "土库曼斯坦", emoji: "🇹🇲" },
  { re: /🇹🇯/i, name: "塔吉克斯坦", emoji: "🇹🇯" },
  { re: /🇰🇬/i, name: "吉尔吉斯斯坦", emoji: "🇰🇬" },
  { re: /🇨🇾/i, name: "塞浦路斯", emoji: "🇨🇾" },
  { re: /🇮🇸/i, name: "冰岛", emoji: "🇮🇸" },
  { re: /🇱🇺/i, name: "卢森堡", emoji: "🇱🇺" },
  { re: /🇸🇰/i, name: "斯洛伐克", emoji: "🇸🇰" },
  { re: /🇧🇬/i, name: "保加利亚", emoji: "🇧🇬" },
  { re: /🇭🇷/i, name: "克罗地亚", emoji: "🇭🇷" },
  { re: /🇸🇮/i, name: "斯洛文尼亚", emoji: "🇸🇮" },
  { re: /🇪🇪/i, name: "爱沙尼亚", emoji: "🇪🇪" },
  { re: /🇱🇻/i, name: "拉脱维亚", emoji: "🇱🇻" },
  { re: /🇱🇹/i, name: "立陶宛", emoji: "🇱🇹" },
  { re: /🇧🇾/i, name: "白俄罗斯", emoji: "🇧🇾" },
  { re: /🇲🇩/i, name: "摩尔多瓦", emoji: "🇲🇩" },
  { re: /🇦🇱/i, name: "阿尔巴尼亚", emoji: "🇦🇱" },
  { re: /🇧🇦/i, name: "波黑共和国", emoji: "🇧🇦" },
  { re: /🇲🇪/i, name: "黑山", emoji: "🇲🇪" },
  { re: /🇲🇰/i, name: "北马其顿", emoji: "🇲🇰" },
  { re: /🇲🇹/i, name: "马耳他", emoji: "🇲🇹" },
  { re: /🇲🇨/i, name: "摩纳哥", emoji: "🇲🇨" },
  { re: /🇦🇩/i, name: "安道尔", emoji: "🇦🇩" },
  { re: /🇱🇮/i, name: "列支敦士登", emoji: "🇱🇮" },
  { re: /🇸🇲/i, name: "圣马力诺", emoji: "🇸🇲" },
  { re: /🇻🇦/i, name: "梵蒂冈", emoji: "🇻🇦" },
  { re: /🇮🇲/i, name: "马恩岛", emoji: "🇮🇲" },
  { re: /🇯🇪/i, name: "泽西岛", emoji: "🇯🇪" },
  { re: /🇬🇬/i, name: "根西岛", emoji: "🇬🇬" },
  { re: /🇫🇴/i, name: "法罗群岛", emoji: "🇫🇴" },
  { re: /🇬🇮/i, name: "直布罗陀", emoji: "🇬🇮" },
  { re: /🇬🇱/i, name: "格陵兰", emoji: "🇬🇱" },
  { re: /🇵🇦/i, name: "巴拿马", emoji: "🇵🇦" },
  { re: /🇨🇷/i, name: "哥斯达黎加", emoji: "🇨🇷" },
  { re: /🇬🇹/i, name: "危地马拉", emoji: "🇬🇹" },
  { re: /🇭🇳/i, name: "洪都拉斯", emoji: "🇭🇳" },
  { re: /🇸🇻/i, name: "萨尔瓦多", emoji: "🇸🇻" },
  { re: /🇳🇮/i, name: "尼加拉瓜", emoji: "🇳🇮" },
  { re: /🇨🇺/i, name: "古巴", emoji: "🇨🇺" },
  { re: /🇩🇴/i, name: "多米尼加", emoji: "🇩🇴" },
  { re: /🇵🇷/i, name: "波多黎各", emoji: "🇵🇷" },
  { re: /🇯🇲/i, name: "牙买加", emoji: "🇯🇲" },
  { re: /🇹🇹/i, name: "特立尼达和多巴哥", emoji: "🇹🇹" },
  { re: /🇧🇸/i, name: "巴哈马", emoji: "🇧🇸" },
  { re: /🇧🇧/i, name: "巴巴多斯", emoji: "🇧🇧" },
  { re: /🇱🇨/i, name: "圣卢西亚", emoji: "🇱🇨" },
  { re: /🇬🇩/i, name: "格林纳达", emoji: "🇬🇩" },
  { re: /🇭🇹/i, name: "海地", emoji: "🇭🇹" },
  { re: /🇺🇾/i, name: "乌拉圭", emoji: "🇺🇾" },
  { re: /🇵🇾/i, name: "巴拉圭", emoji: "🇵🇾" },
  { re: /🇧🇴/i, name: "玻利维亚", emoji: "🇧🇴" },
  { re: /🇪🇨/i, name: "厄瓜多尔", emoji: "🇪🇨" },
  { re: /🇻🇪/i, name: "委内瑞拉", emoji: "🇻🇪" },
  { re: /🇬🇾/i, name: "圭亚那", emoji: "🇬🇾" },
  { re: /🇸🇷/i, name: "苏里南", emoji: "🇸🇷" },
  { re: /🇩🇿/i, name: "阿尔及利亚", emoji: "🇩🇿" },
  { re: /🇲🇦/i, name: "摩洛哥", emoji: "🇲🇦" },
  { re: /🇹🇳/i, name: "突尼斯", emoji: "🇹🇳" },
  { re: /🇱🇾/i, name: "利比亚", emoji: "🇱🇾" },
  { re: /🇳🇬/i, name: "尼日利亚", emoji: "🇳🇬" },
  { re: /🇬🇭/i, name: "加纳", emoji: "🇬🇭" },
  { re: /🇰🇪/i, name: "肯尼亚", emoji: "🇰🇪" },
  { re: /🇹🇿/i, name: "坦桑尼亚", emoji: "🇹🇿" },
  { re: /🇺🇬/i, name: "乌干达", emoji: "🇺🇬" },
  { re: /🇪🇹/i, name: "埃塞俄比亚", emoji: "🇪🇹" },
  { re: /🇷🇼/i, name: "卢旺达", emoji: "🇷🇼" },
  { re: /🇧🇮/i, name: "布隆迪", emoji: "🇧🇮" },
  { re: /🇱🇸/i, name: "莱索托", emoji: "🇱🇸" },
  { re: /🇰🇲/i, name: "科摩罗", emoji: "🇰🇲" },
  { re: /🇸🇿/i, name: "斯威士兰", emoji: "🇸🇿" },
  { re: /🇪🇷/i, name: "厄立特里亚", emoji: "🇪🇷" },
  { re: /🇸🇹/i, name: "圣多美和普林西比", emoji: "🇸🇹" },
  { re: /🇸🇸/i, name: "南苏丹", emoji: "🇸🇸" },
  { re: /🇸🇩/i, name: "苏丹", emoji: "🇸🇩" },
  { re: /🇨🇮/i, name: "科特迪瓦", emoji: "🇨🇮" },
  { re: /🇨🇲/i, name: "喀麦隆", emoji: "🇨🇲" },
  { re: /🇦🇴/i, name: "安哥拉", emoji: "🇦🇴" },
  { re: /🇿🇲/i, name: "赞比亚", emoji: "🇿🇲" },
  { re: /🇿🇼/i, name: "津巴布韦", emoji: "🇿🇼" },
  { re: /🇧🇼/i, name: "博茨瓦纳", emoji: "🇧🇼" },
  { re: /🇳🇦/i, name: "纳米比亚", emoji: "🇳🇦" },
  { re: /🇲🇬/i, name: "马达加斯加", emoji: "🇲🇬" },
  { re: /🇷🇸/i, name: "塞尔维亚", emoji: "🇷🇸" },
  { re: /🇸🇾/i, name: "叙利亚", emoji: "🇸🇾" },
  { re: /🇹🇱/i, name: "东帝汶", emoji: "🇹🇱" },
  { re: /🇨🇫/i, name: "中非共和国", emoji: "🇨🇫" },
  { re: /🇧🇿/i, name: "伯利兹", emoji: "🇧🇿" },
  { re: /🇦🇬/i, name: "安提瓜和巴布达", emoji: "🇦🇬" },
  { re: /🇰🇳/i, name: "圣基茨和尼维斯", emoji: "🇰🇳" },
  { re: /🇻🇨/i, name: "圣文森特和格林纳丁斯", emoji: "🇻🇨" },
  { re: /🇨🇰/i, name: "库克群岛", emoji: "🇨🇰" },
  { re: /🇳🇺/i, name: "纽埃", emoji: "🇳🇺" },
  { re: /🇳🇷/i, name: "瑙鲁", emoji: "🇳🇷" },
  { re: /🇵🇼/i, name: "帕劳", emoji: "🇵🇼" },
  { re: /🇹🇰/i, name: "托克劳", emoji: "🇹🇰" },
  { re: /🇹🇻/i, name: "图瓦卢", emoji: "🇹🇻" },
  { re: /🇰🇮/i, name: "基里巴斯", emoji: "🇰🇮" },
  { re: /🇲🇭/i, name: "马绍尔群岛", emoji: "🇲🇭" },
  { re: /🇫🇲/i, name: "密克罗尼西亚", emoji: "🇫🇲" },
  { re: /🇲🇵/i, name: "北马里亚纳群岛", emoji: "🇲🇵" },
  { re: /🇦🇸/i, name: "美属萨摩亚", emoji: "🇦🇸" },
  { re: /🇼🇸/i, name: "萨摩亚", emoji: "🇼🇸" },
  { re: /🇼🇫/i, name: "瓦利斯和富图纳", emoji: "🇼🇫" },
  { re: /🇽🇰/i, name: "科索沃", emoji: "🇽🇰" },
  { re: /🇦🇼/i, name: "荷属阿鲁巴", emoji: "🇦🇼" },
  { re: /🇧🇲/i, name: "百慕大", emoji: "🇧🇲" },
  { re: /🇰🇾/i, name: "开曼群岛", emoji: "🇰🇾" },
  { re: /🇨🇼/i, name: "荷属库拉索", emoji: "🇨🇼" },
  { re: /🇵🇫/i, name: "法属波利尼西亚", emoji: "🇵🇫" },
  { re: /🇲🇸/i, name: "蒙特塞拉特", emoji: "🇲🇸" },
  { re: /🇸🇽/i, name: "荷属圣马丁", emoji: "🇸🇽" },
  { re: /🇧🇶/i, name: "荷属加勒比", emoji: "🇧🇶" },
  { re: /🇲🇫/i, name: "法属圣马丁", emoji: "🇲🇫" },
  { re: /🇧🇱/i, name: "圣巴泰勒米", emoji: "🇧🇱" },
  { re: /🇫🇰/i, name: "福克兰群岛", emoji: "🇫🇰" },
  { re: /🇳🇫/i, name: "诺福克岛", emoji: "🇳🇫" },
  { re: /🇦🇽/i, name: "奥兰群岛", emoji: "🇦🇽" },
  { re: /🇬🇲/i, name: "冈比亚", emoji: "🇬🇲" },
  { re: /🇬🇼/i, name: "几内亚比绍", emoji: "🇬🇼" },
  { re: /🇱🇷/i, name: "利比里亚", emoji: "🇱🇷" },
  { re: /🇲🇼/i, name: "马拉维", emoji: "🇲🇼" },
  { re: /🇲🇱/i, name: "马里", emoji: "🇲🇱" },
  { re: /🇲🇷/i, name: "毛里塔尼亚", emoji: "🇲🇷" },
  { re: /🇳🇪/i, name: "尼日尔", emoji: "🇳🇪" },
  { re: /🇹🇬/i, name: "多哥", emoji: "🇹🇬" },
  { re: /🇸🇱/i, name: "塞拉利昂", emoji: "🇸🇱" },
  { re: /🇻🇺/i, name: "瓦努阿图", emoji: "🇻🇺" },
  { re: /🇹🇴/i, name: "汤加", emoji: "🇹🇴" },
  { re: /🇸🇧/i, name: "所罗门群岛", emoji: "🇸🇧" },
  { re: /🇲🇺/i, name: "毛里求斯", emoji: "🇲🇺" },
  { re: /🇸🇨/i, name: "塞舌尔", emoji: "🇸🇨" },
  { re: /🇸🇳/i, name: "塞内加尔", emoji: "🇸🇳" },
  { re: /🇧🇫/i, name: "布基纳法索", emoji: "🇧🇫" },
  { re: /🇹🇩/i, name: "乍得", emoji: "🇹🇩" },
  { re: /🇧🇯/i, name: "贝宁", emoji: "🇧🇯" },
  { re: /🇵🇬/i, name: "巴布亚新几内亚", emoji: "🇵🇬" },
  { re: /🇬🇶/i, name: "赤道几内亚", emoji: "🇬🇶" },
  { re: /🇬🇳/i, name: "几内亚", emoji: "🇬🇳" },
  { re: /🇬🇦/i, name: "加蓬", emoji: "🇬🇦" },
  { re: /🇨🇩/i, name: "刚果（金)", emoji: "🇨🇩" },
  { re: /🇨🇬/i, name: "刚果（布)", emoji: "🇨🇬" },
  { re: /🇲🇿/i, name: "莫桑比克", emoji: "🇲🇿" },
  { re: /🇨🇻/i, name: "佛得角", emoji: "🇨🇻" },
  { re: /🇩🇯/i, name: "吉布提", emoji: "🇩🇯" },
  { re: /🇸🇴/i, name: "索马里", emoji: "🇸🇴" },
  { re: /🇫🇯/i, name: "斐济", emoji: "🇫🇯" },
  { re: /🇬🇺/i, name: "关岛", emoji: "🇬🇺" },
  { re: /🇳🇨/i, name: "新喀里多尼亚", emoji: "🇳🇨" },
  { re: /🇦🇶/i, name: "南极洲", emoji: "🇦🇶" },
  { re: /🇵🇸/i, name: "巴勒斯坦", emoji: "🇵🇸" },
  { re: /🇷🇪/i, name: "法属留尼汪", emoji: "🇷🇪" },
  { re: /🇲🇶/i, name: "法属马提尼克", emoji: "🇲🇶" },
  { re: /🇬🇵/i, name: "法属瓜德罗普", emoji: "🇬🇵" },
  { re: /🇾🇹/i, name: "马约特", emoji: "🇾🇹" },
  { re: /🇬🇫/i, name: "法属圭亚那", emoji: "🇬🇫" },
  { re: /🇻🇬/i, name: "英属维尔京群岛", emoji: "🇻🇬" },
  { re: /🇻🇮/i, name: "美属维尔京群岛", emoji: "🇻🇮" },
  { re: /🇹🇨/i, name: "特克斯和凯科斯群岛", emoji: "🇹🇨" },
  { re: /🇦🇮/i, name: "安圭拉", emoji: "🇦🇮" },
  { re: /🇵🇲/i, name: "圣皮埃尔和密克隆群岛", emoji: "🇵🇲" },
  { re: /🇩🇲/i, name: "多米尼克", emoji: "🇩🇲" },
  { re: /🇨🇳/i, name: "中国大陆", emoji: "🇨🇳" }
];

function operator(pro) {
  const regionStats = {};
  const processed = pro
    .filter(p => !(config.clear && RE_CLEAR.test(p.name)))
    .map(p => {
      let matched = REGIONS.find(r => r.re.test(p.name));
      if (!matched) return p;
      
      regionStats[matched.name] = (regionStats[matched.name] || 0) + 1;
      return { ...p, region: matched, isHome: RE_HOME.test(p.name) };
    });

  const counts = {};
  return processed.map(p => {
    if (!p.region) return p;
    
    const regionName = p.region.name;
    const totalInRegion = regionStats[regionName];
    counts[regionName] = (counts[regionName] || 0) + 1;

    const parts = [];
    if (config.flag) parts.push(p.region.emoji);
    parts.push(regionName);
    
    if (totalInRegion > 1) {
      parts.push(String(counts[regionName]).padStart(2, '0'));
    }
    
    if (p.isHome) parts.push("家宽");

    p.name = parts.join(config.fgf);
    return p;
  });
}
