// 2026-02-27 09:07

const inArg = $arguments;
const boolArg = (v, d = false) => {
  if (v == null || v === "") return d;
  return /^(true|1|on|yes)$/i.test(v) ? true : /^(false|0|off|no)$/i.test(v) ? false : !!v;
};

const config = {
  clear: boolArg(inArg.clear, true),
  flag:  boolArg(inArg.flag, true),
  fgf:   inArg.fgf ? decodeURI(inArg.fgf) : " ",
};

const RE_CLEAR = /(GB|TB|PB|TG|频道|免费|套餐|到期|剩余|过期|测试|官网|订阅|流量|机场|联系|客服|有效|重置|网站|地址|20\d{2})/i;
const RE_HOME = /(家宽|住宅|ISP|Home|Residential)/i;

const REGIONS = [
  { re: /香港|\bHK\b|\bHong\s?Kong\b|🇭🇰/i, name: "香港", emoji: "🇭🇰" },
  { re: /台湾|\bTW\b|\bTaiwan\b|🇹🇼/i, name: "台湾", emoji: "🇨🇳" },
  { re: /澳门|\bMO\b|\bMacao\b|🇲🇴/i, name: "澳门", emoji: "🇲🇴" },
  { re: /日本|\bJP\b|\bJapan\b|🇯🇵/i, name: "日本", emoji: "🇯🇵" },
  { re: /韩国|\bKR\b|\bKorea\b|🇰🇷/i, name: "韩国", emoji: "🇰🇷" },
  { re: /新加坡|\bSG\b|\bSingapore\b|🇸🇬/i, name: "新加坡", emoji: "🇸🇬" },
  { re: /美国|\bUS\b|\bUSA\b|\bUnited\s?States\b|🇺🇸/i, name: "美国", emoji: "🇺🇸" },
  { re: /英国|\bUK\b|\bUnited\s?Kingdom\b|\bBritain\b|🇬🇧/i, name: "英国", emoji: "🇬🇧" },
  { re: /越南|\bVN\b|\bVietnam\b|🇻🇳/i, name: "越南", emoji: "🇻🇳" },
  { re: /德国|\bDE\b|\bGermany\b|🇩🇪/i, name: "德国", emoji: "🇩🇪" },
  { re: /法国|\bFR\b|\bFrance\b|🇫🇷/i, name: "法国", emoji: "🇫🇷" },
  { re: /俄罗斯|\bRU\b|\bRussia\b|🇷🇺/i, name: "俄罗斯", emoji: "🇷🇺" },
  { re: /泰国|\bTH\b|\bThailand\b|🇹🇭/i, name: "泰国", emoji: "🇹🇭" },
  { re: /菲律宾|\bPH\b|\bPhilippines\b|🇵🇭/i, name: "菲律宾", emoji: "🇵🇭" },
  { re: /马来西亚|\bMY\b|\bMalaysia\b|🇲🇾/i, name: "马来西亚", emoji: "🇲🇾" },
  { re: /土耳其|\bTR\b|\bTurkey\b|🇹🇷/i, name: "土耳其", emoji: "🇹🇷" },
  { re: /印度|\bIN\b|\bIndia\b|🇮🇳/i, name: "印度", emoji: "🇮🇳" },
  { re: /印尼|\bID\b|\bIndonesia\b|🇮🇩/i, name: "印尼", emoji: "🇮🇩" },
  { re: /以色列|\bIL\b|\bIsrael\b|🇮🇱/i, name: "以色列", emoji: "🇮🇱" },
  { re: /亚美尼亚|\bAM\b|\bArmenia\b/i, name: "亚美尼亚", emoji: "🇦🇲" },
  { re: /澳大利亚|\bAU\b|\bAustralia\b|🇦🇺/i, name: "澳大利亚", emoji: "🇦🇺" },
  { re: /新西兰|\bNZ\b|\bNew\s?Zealand\b|🇳🇿/i, name: "新西兰", emoji: "🇳🇿" },
  { re: /加拿大|\bCA\b|\bCanada\b|🇨🇦/i, name: "加拿大", emoji: "🇨🇦" },
  { re: /墨西哥|\bMX\b|\bMexico\b|🇲🇽/i, name: "墨西哥", emoji: "🇲🇽" },
  { re: /巴西|\bBR\b|\bBrazil\b|🇧🇷/i, name: "巴西", emoji: "🇧🇷" },
  { re: /阿根廷|\bAR\b|\bArgentina\b|🇦🇷/i, name: "阿根廷", emoji: "🇦🇷" },
  { re: /智利|\bCL\b|\bChile\b|🇨🇱/i, name: "智利", emoji: "🇨🇱" },
  { re: /哥伦比亚|\bCO\b|\bColombia\b|🇨🇴/i, name: "哥伦比亚", emoji: "🇨🇴" },
  { re: /秘鲁|\bPE\b|\bPeru\b|🇵🇪/i, name: "秘鲁", emoji: "🇵🇪" },
  { re: /意大利|\bIT\b|\bItaly\b|🇮🇹/i, name: "意大利", emoji: "🇮🇹" },
  { re: /西班牙|\bES\b|\bSpain\b|🇪🇸/i, name: "西班牙", emoji: "🇪🇸" },
  { re: /荷兰|\bNL\b|\bNetherlands\b|🇳🇱/i, name: "荷兰", emoji: "🇳🇱" },
  { re: /瑞士|\bCH\b|\bSwitzerland\b|🇨🇭/i, name: "瑞士", emoji: "🇨🇭" },
  { re: /瑞典|\bSE\b|\bSweden\b|🇸🇪/i, name: "瑞典", emoji: "🇸🇪" },
  { re: /挪威|\bNO\b|\bNorway\b|🇳🇴/i, name: "挪威", emoji: "🇳🇴" },
  { re: /丹麦|\bDK\b|\bDenmark\b|🇩🇰/i, name: "丹麦", emoji: "🇩🇰" },
  { re: /芬兰|\bFI\b|\bFinland\b|🇫🇮/i, name: "芬兰", emoji: "🇫🇮" },
  { re: /奥地利|\bAT\b|\bAustria\b|🇦🇹/i, name: "奥地利", emoji: "🇦🇹" },
  { re: /比利时|\bBE\b|\bBelgium\b|🇧🇪/i, name: "比利时", emoji: "🇧🇪" },
  { re: /爱尔兰|\bIE\b|\bIreland\b|🇮🇪/i, name: "爱尔兰", emoji: "🇮🇪" },
  { re: /葡萄牙|\bPT\b|\bPortugal\b|🇵🇹/i, name: "葡萄牙", emoji: "🇵🇹" },
  { re: /希腊|\bGR\b|\bGreece\b|🇬🇷/i, name: "希腊", emoji: "🇬🇷" },
  { re: /捷克|\bCZ\b|\bCzech\b|🇨🇿/i, name: "捷克", emoji: "🇨🇿" },
  { re: /波兰|\bPL\b|\bPoland\b|🇵🇱/i, name: "波兰", emoji: "🇵🇱" },
  { re: /乌克兰|\bUA\b|\bUkraine\b|🇺🇦/i, name: "乌克兰", emoji: "🇺🇦" },
  { re: /罗马尼亚|\bRO\b|\bRomania\b|🇷🇴/i, name: "罗马尼亚", emoji: "🇷🇴" },
  { re: /匈牙利|\bHU\b|\bHungary\b|🇭🇺/i, name: "匈牙利", emoji: "🇭🇺" },
  { re: /阿联酋|\bAE\b|\bUAE\b|🇦🇪/i, name: "阿联酋", emoji: "🇦🇪" },
  { re: /沙特|\bSA\b|\bSaudi\s?Arabia\b|🇸🇦/i, name: "沙特", emoji: "🇸🇦" },
  { re: /南非|\bZA\b|\bSouth\s?Africa\b|\bJohannesburg\b|🇿🇦/i, name: "南非", emoji: "🇿🇦" },
  { re: /埃及|\bEG\b|\bEgypt\b|🇪🇬/i, name: "埃及", emoji: "🇪🇬" },
  { re: /柬埔寨|\bKH\b|\bCambodia\b|🇰🇭/i, name: "柬埔寨", emoji: "🇰🇭" },
  { re: /缅甸|\bMM\b|\bMyanmar\b|🇲🇲/i, name: "缅甸", emoji: "🇲🇲" },
  { re: /老挝|\bLA\b|\bLaos\b|🇱🇦/i, name: "老挝", emoji: "🇱🇦" },
  { re: /巴基斯坦|\bPK\b|\bPakistan\b|🇵🇰/i, name: "巴基斯坦", emoji: "🇵🇰" },
  { re: /哈萨克斯坦|\bKZ\b|\bKazakhstan\b|🇰🇿/i, name: "哈萨克斯坦", emoji: "🇰🇿" },
  { re: /乌兹别克斯坦|\bUZ\b|\bUzbekistan\b|🇺🇿/i, name: "乌兹别克斯坦", emoji: "🇺🇿" },
  { re: /约旦|\bJO\b|\bJordan\b|🇯🇴/i, name: "约旦", emoji: "🇯🇴" },
  { re: /卡塔尔|\bQA\b|\bQatar\b|🇶🇦/i, name: "卡塔尔", emoji: "🇶🇦" },
  { re: /科威特|\bKW\b|\bKuwait\b|🇰🇼/i, name: "科威特", emoji: "🇰🇼" },
  { re: /孟加拉|\bBD\b|\bBangladesh\b|🇧🇩/i, name: "孟加拉", emoji: "🇧🇩" },
  { re: /斯里兰卡|\bLK\b|\bSri\s?Lanka\b|🇱🇰/i, name: "斯里兰卡", emoji: "🇱🇰" },
  { re: /尼泊尔|\bNP\b|\bNepal\b|🇳🇵/i, name: "尼泊尔", emoji: "🇳🇵" },
  { re: /蒙古|\bMN\b|\bMongolia\b|🇲🇳/i, name: "蒙古", emoji: "🇲🇳" },
  { re: /马尔代夫|\bMV\b|\bMaldives\b|🇲🇻/i, name: "马尔代夫", emoji: "🇲🇻" },
  { re: /不丹|\bBT\b|\bBhutan\b|🇧🇹/i, name: "不丹", emoji: "🇧🇹" },
  { re: /文莱|\bBN\b|\bBrunei\b|🇧🇳/i, name: "文莱", emoji: "🇧🇳" },
  { re: /阿富汗|\bAF\b|\bAfghanistan\b|🇦🇫/i, name: "阿富汗", emoji: "🇦🇫" },
  { re: /伊拉克|\bIQ\b|\bIraq\b|🇮🇶/i, name: "伊拉克", emoji: "🇮🇶" },
  { re: /黎巴嫩|\bLB\b|\bLebanon\b|🇱🇧/i, name: "黎巴嫩", emoji: "🇱🇧" },
  { re: /也门|\bYE\b|\bYemen\b|🇾🇪/i, name: "也门", emoji: "🇾🇪" },
  { re: /阿曼|\bOM\b|\bOman\b|🇴🇲/i, name: "阿曼", emoji: "🇴🇲" },
  { re: /巴林|\bBH\b|\bBahrain\b|🇧🇭/i, name: "巴林", emoji: "🇧🇭" },
  { re: /格鲁吉亚|\bGE\b|\bGeorgia\b|🇬🇪/i, name: "格鲁吉亚", emoji: "🇬🇪" },
  { re: /阿塞拜疆|\bAZ\b|\bAzerbaijan\b|🇦🇿/i, name: "阿塞拜疆", emoji: "🇦🇿" },
  { re: /土库曼斯坦|\bTM\b|\bTurkmenistan\b|🇹🇲/i, name: "土库曼斯坦", emoji: "🇹🇲" },
  { re: /塔吉克斯坦|\bTJ\b|\bTajikistan\b|🇹🇯/i, name: "塔吉克斯坦", emoji: "🇹🇯" },
  { re: /吉尔吉斯斯坦|\bKG\b|\bKyrgyzstan\b|🇰🇬/i, name: "吉尔吉斯斯坦", emoji: "🇰🇬" },
  { re: /塞浦路斯|\bCY\b|\bCyprus\b|🇨🇾/i, name: "塞浦路斯", emoji: "🇨🇾" },
  { re: /冰岛|\bIS\b|\bIceland\b|🇮🇸/i, name: "冰岛", emoji: "🇮🇸" },
  { re: /卢森堡|\bLU\b|\bLuxembourg\b|🇱🇺/i, name: "卢森堡", emoji: "🇱🇺" },
  { re: /斯洛伐克|\bSK\b|\bSlovakia\b|🇸🇰/i, name: "斯洛伐克", emoji: "🇸🇰" },
  { re: /保加利亚|\bBG\b|\bBulgaria\b|🇧🇬/i, name: "保加利亚", emoji: "🇧🇬" },
  { re: /克罗地亚|\bHR\b|\bCroatia\b|🇭🇷/i, name: "克罗地亚", emoji: "🇭🇷" },
  { re: /斯洛文尼亚|\bSI\b|\bSlovenia\b|🇸🇮/i, name: "斯洛文尼亚", emoji: "🇸🇮" },
  { re: /爱沙尼亚|\bEE\b|\bEstonia\b|🇪🇪/i, name: "爱沙尼亚", emoji: "🇪🇪" },
  { re: /拉脱维亚|\bLV\b|\bLatvia\b|🇱🇻/i, name: "拉脱维亚", emoji: "🇱🇻" },
  { re: /立陶宛|\bLT\b|\bLithuania\b|🇱🇹/i, name: "立陶宛", emoji: "🇱🇹" },
  { re: /白俄罗斯|\bBY\b|\bBelarus\b|🇧🇾/i, name: "白俄罗斯", emoji: "🇧🇾" },
  { re: /摩尔多瓦|\bMD\b|\bMoldova\b|🇲🇩/i, name: "摩尔多瓦", emoji: "🇲🇩" },
  { re: /阿尔巴尼亚|\bAL\b|\bAlbania\b|🇦🇱/i, name: "阿尔巴尼亚", emoji: "🇦🇱" },
  { re: /波黑|\bBA\b|\bBosnia\b|🇧🇦/i, name: "波黑", emoji: "🇧🇦" },
  { re: /黑山|\bME\b|\bMontenegro\b|🇲🇪/i, name: "黑山", emoji: "🇲🇪" },
  { re: /北马其顿|\bMK\b|\bMacedonia\b|🇲🇰/i, name: "北马其顿", emoji: "🇲🇰" },
  { re: /马耳他|\bMT\b|\bMalta\b|🇲🇹/i, name: "马耳他", emoji: "🇲🇹" },
  { re: /摩纳哥|\bMC\b|\bMonaco\b|🇲🇨/i, name: "摩纳哥", emoji: "🇲🇨" },
  { re: /安道尔|\bAD\b|\bAndorra\b|🇦🇩/i, name: "安道尔", emoji: "🇦🇩" },
  { re: /列支敦士登|\bLI\b|\bLiechtenstein\b|🇱🇮/i, name: "列支敦士登", emoji: "🇱🇮" },
  { re: /圣马力诺|\bSM\b|\bSan\s?Marino\b|🇸🇲/i, name: "圣马力诺", emoji: "🇸🇲" },
  { re: /梵蒂冈|\bVA\b|\bVatican\b|🇻🇦/i, name: "梵蒂冈", emoji: "🇻🇦" },
  { re: /马恩岛|\bIM\b|\bIsle\s?of\s?Man\b|🇮🇲/i, name: "马恩岛", emoji: "🇮🇲" },
  { re: /泽西岛|\bJE\b|\bJersey\b|🇯🇪/i, name: "泽西岛", emoji: "🇯🇪" },
  { re: /根西岛|\bGG\b|\bGuernsey\b|🇬🇬/i, name: "根西岛", emoji: "🇬🇬" },
  { re: /法罗群岛|\bFO\b|\bFaroe\b|🇫🇴/i, name: "法罗群岛", emoji: "🇫🇴" },
  { re: /直布罗陀|\bGI\b|\bGibraltar\b|🇬🇮/i, name: "直布罗陀", emoji: "🇬🇮" },
  { re: /格陵兰|\bGL\b|\bGreenland\b|🇬🇱/i, name: "格陵兰", emoji: "🇬🇱" },
  { re: /巴拿马|\bPA\b|\bPanama\b|🇵🇦/i, name: "巴拿马", emoji: "🇵🇦" },
  { re: /哥斯达黎加|\bCR\b|\bCosta\s?Rica\b|🇨🇷/i, name: "哥斯达黎加", emoji: "🇨🇷" },
  { re: /危地马拉|\bGT\b|\bGuatemala\b|🇬🇹/i, name: "危地马拉", emoji: "🇬🇹" },
  { re: /洪都拉斯|\bHN\b|\bHonduras\b|🇭🇳/i, name: "洪都拉斯", emoji: "🇭🇳" },
  { re: /萨尔瓦多|\bSV\b|\bSalvador\b|🇸🇻/i, name: "萨尔瓦多", emoji: "🇸🇻" },
  { re: /尼加拉瓜|\bNI\b|\bNicaragua\b|🇳🇮/i, name: "尼加拉瓜", emoji: "🇳🇮" },
  { re: /古巴|\bCU\b|\bCuba\b|🇨🇺/i, name: "古巴", emoji: "🇨🇺" },
  { re: /多米尼加|\bDO\b|\bDominican\b|🇩🇴/i, name: "多米尼加", emoji: "🇩🇴" },
  { re: /波多黎各|\bPR\b|\bPuerto\s?Rico\b|🇵🇷/i, name: "波多黎各", emoji: "🇵🇷" },
  { re: /牙买加|\bJM\b|\bJamaica\b|🇯🇲/i, name: "牙买加", emoji: "🇯🇲" },
  { re: /特立尼达|\bTT\b|\bTrinidad\b|🇹🇹/i, name: "特立尼达和多巴哥", emoji: "🇹🇹" },
  { re: /巴哈马|\bBS\b|\bBahamas\b|🇧🇸/i, name: "巴哈马", emoji: "🇧🇸" },
  { re: /巴巴多斯|\bBB\b|\bBarbados\b|🇧🇧/i, name: "巴巴多斯", emoji: "🇧🇧" },
  { re: /圣卢西亚|\bLC\b|\bSaint\s?Lucia\b|🇱🇨/i, name: "圣卢西亚", emoji: "🇱🇨" },
  { re: /格林纳达|\bGD\b|\bGrenada\b|🇬🇩/i, name: "格林纳达", emoji: "🇬🇩" },
  { re: /乌拉圭|\bUY\b|\bUruguay\b|🇺🇾/i, name: "乌拉圭", emoji: "🇺🇾" },
  { re: /巴拉圭|\bPY\b|\bParaguay\b|🇵🇾/i, name: "巴拉圭", emoji: "🇵🇾" },
  { re: /玻利维亚|\bBO\b|\bBolivia\b|🇧🇴/i, name: "玻利维亚", emoji: "🇧🇴" },
  { re: /厄瓜多尔|\bEC\b|\bEcuador\b|🇪🇨/i, name: "厄瓜多尔", emoji: "🇪🇨" },
  { re: /委内瑞拉|\bVE\b|\bVenezuela\b|🇻🇪/i, name: "委内瑞拉", emoji: "🇻🇪" },
  { re: /圭亚那|\bGY\b|\bGuyana\b|🇬🇾/i, name: "圭亚那", emoji: "🇬🇾" },
  { re: /苏里南|\bSR\b|\bSuriname\b|🇸🇷/i, name: "苏里南", emoji: "🇸🇷" },
  { re: /阿尔及利亚|\bDZ\b|\bAlgeria\b|🇩🇿/i, name: "阿尔及利亚", emoji: "🇩🇿" },
  { re: /摩洛哥|\bMA\b|\bMorocco\b|🇲🇦/i, name: "摩洛哥", emoji: "🇲🇦" },
  { re: /突尼斯|\bTN\b|\bTunisia\b|🇹🇳/i, name: "突尼斯", emoji: "🇹🇳" },
  { re: /利比亚|\bLY\b|\bLibya\b|🇱🇾/i, name: "利比亚", emoji: "🇱🇾" },
  { re: /尼日利亚|\bNG\b|\bNigeria\b|🇳🇬/i, name: "尼日利亚", emoji: "🇳🇬" },
  { re: /加纳|\bGH\b|\bGhana\b|🇬🇭/i, name: "加纳", emoji: "🇬🇭" },
  { re: /肯尼亚|\bKE\b|\bKenya\b|🇰🇪/i, name: "肯尼亚", emoji: "🇰🇪" },
  { re: /坦桑尼亚|\bTZ\b|\bTanzania\b|🇹🇿/i, name: "坦桑尼亚", emoji: "🇹🇿" },
  { re: /乌干达|\bUG\b|\bUganda\b|🇺🇬/i, name: "乌干达", emoji: "🇺🇬" },
  { re: /埃塞尾比亚|\bET\b|\bEthiopia\b|🇪🇹/i, name: "埃塞俄比亚", emoji: "🇪🇹" },
  { re: /苏丹|\bSD\b|\bSudan\b|🇸🇩/i, name: "苏丹", emoji: "🇸🇩" },
  { re: /科特迪瓦|\bCI\b|\bIvory\s?Coast\b|🇨🇮/i, name: "科特迪瓦", emoji: "🇨🇮" },
  { re: /喀麦隆|\bCM\b|\bCameroon\b|🇨🇲/i, name: "喀麦隆", emoji: "🇨🇲" },
  { re: /安哥拉|\bAO\b|\bAngola\b|🇦🇴/i, name: "安哥拉", emoji: "🇦🇴" },
  { re: /赞比亚|\bZM\b|\bZambia\b|🇿🇲/i, name: "赞比亚", emoji: "🇿🇲" },
  { re: /津巴布韦|\bZW\b|\bZimbabwe\b|🇿🇼/i, name: "津巴布韦", emoji: "🇿🇼" },
  { re: /博茨瓦纳|\bBW\b|\bBotswana\b|🇧🇼/i, name: "博茨瓦纳", emoji: "🇧🇼" },
  { re: /纳米比亚|\bNA\b|\bNamibia\b|🇳🇦/i, name: "纳米比亚", emoji: "🇳🇦" },
  { re: /马达加斯加|\bMG\b|\bMadagascar\b|🇲🇬/i, name: "马达加斯加", emoji: "🇲🇬" },
  { re: /塞尔维亚|\bRS\b|\bSerbia\b|🇷🇸/i, name: "塞尔维亚", emoji: "🇷🇸" },
  { re: /朝鲜|\bKP\b|\bNorth\s?Korea\b|🇰🇵/i, name: "朝鲜", emoji: "🇰🇵" },
  { re: /叙利亚|\bSY\b|\bSyria\b|🇸🇾/i, name: "叙利亚", emoji: "🇸🇾" },
  { re: /东帝汶|\bTL\b|\bTimor\b|🇹🇱/i, name: "东帝汶", emoji: "🇹🇱" },
  { re: /中非|\bCF\b|\bCentral\s?African\b|🇨🇫/i, name: "中非共和国", emoji: "🇨🇫" },
  { re: /伯利兹|\bBZ\b|\bBelize\b|🇧🇿/i, name: "伯利兹", emoji: "🇧🇿" },
  { re: /安提瓜|\bAG\b|\bAntigua\b|🇦🇬/i, name: "安提瓜和巴布达", emoji: "🇦🇬" },
  { re: /圣基茨|\bKN\b|\bSaint\s?Kitts\b|🇰🇳/i, name: "圣基茨和尼维斯", emoji: "🇰🇳" },
  { re: /圣文森特|\bVC\b|\bSaint\s?Vincent\b|🇻🇨/i, name: "圣文森特和格林纳丁斯", emoji: "🇻🇨" },
  { re: /多米尼克|\bDM\b|🇩🇲/i, name: "多米尼克", emoji: "🇩🇲" },
  { re: /库克群岛|\bCK\b|\bCook\s?Islands\b|🇨🇰/i, name: "库克群岛", emoji: "🇨🇰" },
  { re: /纽埃|\bNU\b|\bNiue\b|🇳🇺/i, name: "纽埃", emoji: "🇳🇺" },
  { re: /科索沃|\bXK\b|\bKosovo\b|🇽🇰/i, name: "科索沃", emoji: "🇽🇰" },
  { re: /阿鲁巴|\bAW\b|\bAruba\b|🇦🇼/i, name: "阿鲁巴", emoji: "🇦🇼" },
  { re: /百慕大|\bBM\b|\bBermuda\b|🇧🇲/i, name: "百慕大", emoji: "🇧🇲" },
  { re: /开曼群岛|\bKY\b|\bCayman\b|🇰🇾/i, name: "开曼群岛", emoji: "🇰🇾" },
  { re: /库拉索|\bCW\b|\bCuracao\b|🇨🇼/i, name: "库拉索", emoji: "🇨🇼" },
  { re: /波利尼西亚|\bPF\b|\bPolynesia\b|🇵🇫/i, name: "法属波利尼西亚", emoji: "🇵🇫" },
  { re: /冈比亚|\bGM\b|\bGambia\b|🇬🇲/i, name: "冈比亚", emoji: "🇬🇲" },
  { re: /几内亚比绍|\bGW\b|\bBissau\b|🇬🇼/i, name: "几内亚比绍", emoji: "🇬🇼" },
  { re: /利比里亚|\bLR\b|\bLiberia\b|🇱🇷/i, name: "利比里亚", emoji: "🇱🇷" },
  { re: /马拉维|\bMW\b|\bMalawi\b|🇲🇼/i, name: "马拉维", emoji: "🇲🇼" },
  { re: /马里|\bML\b|\bMali\b|🇲🇱/i, name: "马里", emoji: "🇲🇱" },
  { re: /毛里塔尼亚|\bMR\b|\bMauritania\b|🇲🇷/i, name: "毛里塔尼亚", emoji: "🇲🇷" },
  { re: /尼日尔|\bNE\b|\bNiger\b|🇳🇪/i, name: "尼日尔", emoji: "🇳🇪" },
  { re: /多哥|\bTG\b|\bTogo\b|🇹🇬/i, name: "多哥", emoji: "🇹🇬" },
  { re: /塞拉利昂|\bSL\b|\bSierra\s?Leone\b|🇸🇱/i, name: "塞拉利昂", emoji: "🇸🇱" },
  { re: /瓦努阿图|\bVU\b|\bVanuatu\b|🇻🇺/i, name: "瓦努阿图", emoji: "🇻🇺" },
  { re: /汤加|\bTO\b|\bTonga\b|🇹🇴/i, name: "汤加", emoji: "🇹🇴" },
  { re: /萨摩亚|\bWS\b|\bSamoa\b|🇼🇸/i, name: "萨摩亚", emoji: "🇼🇸" },
  { re: /所罗门群岛|\bSB\b|\bSolomon\b|🇸🇧/i, name: "所罗门群岛", emoji: "🇸🇧" },
  { re: /毛里求斯|\bMU\b|\bMauritius\b|🇲🇺/i, name: "毛里求斯", emoji: "🇲🇺" },
  { re: /塞舌尔|\bSC\b|\bSeychelles\b|🇸🇨/i, name: "塞舌尔", emoji: "🇸🇨" },
  { re: /塞内加尔|\bSN\b|\bSenegal\b|🇸🇳/i, name: "塞内加尔", emoji: "🇸🇳" },
  { re: /布基纳法索|\bBF\b|\bBurkina\b|🇧🇫/i, name: "布基纳法索", emoji: "🇧🇫" },
  { re: /乍得|\bTD\b|\bChad\b|🇹🇩/i, name: "乍得", emoji: "🇹🇩" },
  { re: /贝宁|\bBJ\b|\bBenin\b|🇧🇯/i, name: "贝宁", emoji: "🇧🇯" },
  { re: /几内亚|\bGN\b|\bGuinea\b|🇬🇳/i, name: "几内亚", emoji: "🇬🇳" },
  { re: /赤道几内亚|\bGQ\b|\bEquatorial\b|🇬🇶/i, name: "赤道几内亚", emoji: "🇬🇶" },
  { re: /加蓬|\bGA\b|\bGabon\b|🇬🇦/i, name: "加蓬", emoji: "🇬🇦" },
  { re: /刚果（布）|\bCG\b|\bCongo\b|🇨🇬/i, name: "刚果（布)", emoji: "🇨🇬" },
  { re: /刚果（金）|\bCD\b|\bKinshasa\b|🇨🇩/i, name: "刚果（金)", emoji: "🇨🇩" },
  { re: /莫桑比克|\bMZ\b|\bMozambique\b|🇲🇿/i, name: "莫桑比克", emoji: "🇲🇿" },
  { re: /佛得角|\bCV\b|\bCape\s?Verde\b|🇨🇻/i, name: "佛得角", emoji: "🇨🇻" },
  { re: /吉布提|\bDJ\b|\bDjibouti\b|🇩🇯/i, name: "吉布提", emoji: "🇩🇯" },
  { re: /索马里|\bSO\b|\bSomalia\b|🇸🇴/i, name: "索马里", emoji: "🇸🇴" },
  { re: /斐济|\bFJ\b|\bFiji\b|🇫🇯/i, name: "斐济", emoji: "🇫🇯" },
  { re: /巴布亚|\bPG\b|\bPapua\b|🇵🇬/i, name: "巴布亚新几内亚", emoji: "🇵🇬" },
  { re: /关岛|\bGU\b|\bGuam\b|🇬🇺/i, name: "关岛", emoji: "🇬🇺" },
  { re: /新喀里多尼亚|\bNC\b|\bCaledonia\b|🇳🇨/i, name: "新喀里多尼亚", emoji: "🇳🇨" },
  { re: /南极|\bAQ\b|\bAntarctica\b|🇦🇶/i, name: "南极洲", emoji: "🇦🇶" },
  { re: /巴勒斯坦|\bPS\b|\bPalestine\b|🇵🇸/i, name: "巴勒斯坦", emoji: "🇵🇸" },
  { re: /留尼汪|\bRE\b|\bReunion\b|🇷🇪/i, name: "留尼汪", emoji: "🇷🇪" },
  { re: /马提尼克|\bMQ\b|\bMartinique\b|🇲🇶/i, name: "马提尼克", emoji: "🇲🇶" },
  { re: /瓜德罗普|\bGP\b|\bGuadeloupe\b|🇬🇵/i, name: "瓜德罗普", emoji: "🇬🇵" },
  { re: /马约特|\bYT\b|\bMayotte\b|🇾🇹/i, name: "马约特", emoji: "🇾🇹" },
  { re: /法属圭亚那|\bGF\b|\bFrench\s?Guiana\b|🇬🇫/i, name: "法属圭亚那", emoji: "🇬🇫" },
  { re: /维尔京群岛|\bVG\b|\bVirgin\s?Islands\b|🇻🇬/i, name: "英属维尔京群岛", emoji: "🇻🇬" },
  { re: /美属维尔京|\bVI\b|\bUnited\s?States\s?Virgin\b|🇻🇮/i, name: "美属维尔京群岛", emoji: "🇻🇮" },
  { re: /特克斯|\bTC\b|\bTurks\b|🇹🇨/i, name: "特克斯和凯科斯", emoji: "🇹🇨" },
  { re: /安圭拉|\bAI\b|\bAnguilla\b|🇦🇮/i, name: "安圭拉", emoji: "🇦🇮" },
  { re: /圣皮埃尔|\bPM\b|\bMiquelon\b|🇵🇲/i, name: "圣皮埃尔和密克隆", emoji: "🇵🇲" },
  { re: /中国|\bCN\b|\bChina\b|🇨🇳/i, name: "中国大陆", emoji: "🇨🇳" }
];

function operator(pro) {
  const counts = {};
  return pro
    .filter(p => !(config.clear && RE_CLEAR.test(p.name)))
    .map(p => {
      let matched = REGIONS.find(r => r.re.test(p.name));
      
      if (!matched) return p;

      const isHome = RE_HOME.test(p.name);
      
      counts[matched.name] = (counts[matched.name] || 0) + 1;
      const num = String(counts[matched.name]).padStart(2, '0');

      const parts = [];
      if (config.flag) parts.push(matched.emoji);
      parts.push(matched.name);
      parts.push(num);
      if (isHome) parts.push("家宽");

      p.name = parts.join(config.fgf);
      return p;
    })
    .filter(p => p !== null);
}
